version: "3"

services:
    #抢票服务
    ticket:
        build:
            context: .
            dockerfile: ./Dockerfile37
        image: ticket:v1.2.004
        environment:
            - PYTHONUNBUFFERED=1
            - CAPTCHALOCAL=1
        container_name: ticket
        networks:
            - 12306network
        restart: on-failure
networks:
    12306network:
        driver: bridge

